### PR TITLE
Updated version of the F# client

### PR DESCRIPTION
**Pull request by essic**
Update Suave
Setting up FAKE and PAKET to run the solution
Code clean up and small improvement.

A solution to the kata is avaiable in my repo on the branch fsharp-test

### CODE REVIEW

**Comment by essic** [comment]
The branch name has changed, it's "solutions" now.

**Comment by dlresende** [comment]
Hi @essic,

Thank you for your PR and sorry for taking that long to review it.

One question before merging it: do we need to commit the exe files? I'm not a F#/C# coder, but it always seems wired to me to commit binaries.

**Comment by essic** [comment]
Hi @dlresende,

I was thinking that you forgot about the PR -)
Thanks for remembering.

It is indeed bad practice normally but I took the habit of commiting .paket.bootstraper.exe because of the advice given here : https://fsprojects.github.io/Paket/faq.html#What-files-should-I-commit

I wanted people to be able to start straight away.

For the paket.exe it is my mistake, sorry, can you remove it or should I ? If you do can you add please links toward Paket and Fake ?

**Comment by dlresende** [comment]
No pb :)
I let you remove it and add the link, so that I can merge it.
Thank you!

**Comment by essic** [comment]
Here we go.
I remove paket.exe and updated .gitignore and README.md

It should ok now.
Thanks

**Pull request merged**
