### PR TITLE
Add client ruby on rails for ruby

### PR DESCRIPTION
**Pull request by Hettomei**
Bien le bonjour,

Voici ma petite PR suite au dojo de Jeudi.

Encore merci pour l'organisation.

### CODE REVIEW

**Comment by dlresende** [comment]
I'd like to keep the original ruby template without rails and then merge this one.
I need to take some time to create the a `ruby/sinatra` folder to the existing template and put this one to `ruby/rails`.

**Comment by Hettomei** [comment]
Hi,

I did not understand; I already moved sinatra app into ruby/sinatra. 
How may I help you to finish this PR ?

**Comment by Hettomei** [comment]
Hi, I rebased. Now their is two folder : /sinatra and /rails

Did you need something else ?

**Comment by dlresende** [comment]
Sounds good to me.
Thanks!

**Pull request merged**
