### PR TITLE
Clients improvements

### PR DESCRIPTION
**Pull request by jak78**
Hi,
As I said to Diego, we played the game with many participants: ~80 devs 
That was a challenge! We learned things and we changed several things on the code to make it easier to play with many participants. 
This first pull request provides:
- a batch of improvements to several clients we used during this game: Java & C# - we made them more 'ready-to-use' to make facilitation easier and have less technical problems to handle during the game
- a new JavaScript client using Express as Express was popular for these devs 

Other PRs will come. I hope you will find them useful.
Don't hesitate to contact me for any feedback or if you need more informations.

### CODE REVIEW

**Comment by dlresende** [comment]
hello @jak78,
Many thanks for the PR ;) most changes are indeed very useful.
I'd like to discuss one point tough which regards the steps before really getting into the problem. In the java client for instance, we believe that since the language itself doesn't give any "magic" serialization solution, you should write your own serializer class based on your needs. For that reason, we decided to not give the Order serializer and leave it to be took in charge by teams. Two arguments here: 

1. we tried to "respect" strengths and drawbacks of each language and do not balance by giving ready to use stuff. Philosophy behind: you chose the language you are familiar with and accept pros and cons, and you don't chose clients based on how advanced the client is regarding the "stuff to be done";
2. we'd like people to deal also with technical issues and not only with issues related to the problem itself. In real life this happens all the time, and as per my comprehension, there is no reason that for the exercise drop tech constraints. Otherwise, we'd like to allow people to use their own stack that is maybe not in the client list proposed, so providing too many facilities could create a huge gap between people starting from zero and people using provided clients.

Based on your experience running extreme carpaccio, could you argue over those two points? :)

**Comment by jak78** [comment]
Hello @dlresende 
Thanks four your feedback!
When I ran Extreme Carpaccio several times, I observed that people that choosed Java where struggling with (de)serialization problems, while at the same time other people were able to play. 
Before these improvements on Java client, I observed that:
- not everyone had fun and they did not learn so much. 
- facilitation was harder, in particular with many participants, because facilitator had to deal with many help requests.
After these improvements, I observed the opposite :-)
I also considered that dealing with these issues was not part of the main goals of the game, but we could argue over this :-)

**Comment by dlresende** [comment]
Ok, let's try this out :)
Thank you  @jak78

**Comment by jak78** [comment]
Thanks for the merge :-)
Le jeu. 10 mars 2016 à 14:26, Diego Lemos <notifications@github.com> a
écrit :

**Pull request merged**
